export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const GET_NOW_PLAYING_ERROR = "GET_NOW_PLAYING_ERROR";
export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE";
export const HYDRATE_FAVOURITES = "HYDRATE_FAVOURITES";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";
export const CLEAR_MOVIE_DETAILS = "CLEAR_MOVIE_DETAILS";
